USE SalesDB;
SELECT * FROM Sales.Orders;
-- FUNCTIONS 

--1] STRING FUNCTIONS
SELECT CONCAT(FirstName,' ', LastName) AS Name FROM Sales.Customers; -- ADDS TWO STRINGS TOGETHER
SELECT UPPER(FirstName) AS Name FROM Sales.Customers; -- CONVERTS STRING INTO UPPERCASE
SELECT LOWER(LastName) AS Name FROM Sales.Customers; -- CONVERTS STRING INTO LOWERCASE
SELECT TRIM(FirstName) AS Name FROM Sales.Customers; -- REMOVES SPACES FROM THE GIVEN STRING
SELECT 'Beacon.docx' AS OLD_FILENAME, REPLACE('Beacon.docx','.docx','.pdf') AS NEW_FILENAME -- REPLACES CERTAIN CHARACTER WITH ANOTHER CHARACTER OF CHOICE 
SELECT LEN(FirstName) AS Length_of_firstname  FROM Sales.Customers; -- RETURNS THE LENGTH OF THE STRING
SELECT LEFT (FirstName, 2) AS FIRST_TWO_CHARACTERS_NAME FROM Sales.Customers; -- EXTRACTS FIRST 2(VARIABLE VALUE) CHARACTERS FROM THE STRING
SELECT RIGHT (FirstName, 3) AS LAST_THREE_CHARACTERS_NAME FROM Sales.Customers; -- EXTRACTS LAST 3(VARIABLE VALUE) CHARACTERS FROM THE STRING
SELECT SUBSTRING(FirstName, 0, 5) AS Name FROM Sales.Customers; -- EXTRACT GIVEN NUMBER OF CHARACTERS AFTER A SPECIFIED INDEX IN THE STRING

--2] NUMBER FUNCTIONS 
SELECT 3.14159265359 AS PIE, ROUND(3.14159265359, 3) AS DECIMAL_VALUE_UPTO_3DIGITS -- ROUNDS ANY GIVEN DECIMAL VALUE UPTO SPECIFIED DIGIT PRECISION
SELECT -10 AS Negative, ABS(-10) AS Positive -- REMOVES ANY NEGATIVE VALUES AND CONVERTS THEM INTO POSITIVE

--3] DATETIME FUNCTIONS 
SELECT DAY(OrderDate), MONTH(OrderDate), YEAR(OrderDate) FROM Sales.Orders; -- RETURNS ONLY THE DAY, MONTH, YEAR VALUE FROM THE DATE  
SELECT DATEPART(DAY, OrderDate), DATEPART(MONTH, OrderDate), DATEPART(YEAR, OrderDate), DATEPART(WEEK, OrderDate), DATEPART(QUARTER, OrderDate) FROM Sales.Orders; -- RETURNS SPECIFIED PART FROM THE GIVEN DATE
SELECT DATENAME(month, OrderDate), DATENAME(weekday, OrderDate) FROM Sales.Orders; -- RETURNS THE NAME OF THE DATE ELEMENT.
SELECT DATETRUNC(minute, CreationTime) FROM Sales.Orders; -- IT IS USED TO RESET THE SMALLER PARTS OF DATETIME VALUE AND RETURN THE DATETIME TRUNCATED TO A SPECIFIED LEVEL
SELECT OrderID, OrderDate, ShipDate, CreationTime, GETDATE() AS QueryExecutionTime FROM Sales.Orders; -- RETURNS THE CURRENT DATE AND TIME AT THE MOMENT WHEN THE QUERY WAS EXECUTED
SELECT FORMAT(OrderDate, 'dd/MM/yyyy') AS Ind_DateFormat FROM Sales.Orders; -- IT IS USED TO CHANGE THE FORMAT OF DATE FROM ONE STANDARD TO ANOTHER
SELECT CONVERT(DATE, '2005-04-25') AS DOB; -- CONVERTS THE DATATYPE OF VARIABLE FROM ONE DATATYPE TO ANOTHER DATATYPE
SELECT CAST(OrderDate AS VARCHAR) FROM Sales.Orders; -- IT AS WELL CONVERTS GIVEN VALUE'S DATATYPE FROM ONE TYPE TO ANOTHER
SELECT DATEADD(YEAR, 2, OrderDate) AS TWO_YEARS_ADDED FROM Sales.Orders; -- IT IS USED TO PERFORM DATE OPERATIONS BY ADDING EITHER DAYS, MONTHS OR YEAR TO A GIVEN DATE
SELECT DATEDIFF(YEAR, '2005-04-25', '2026-08-14') AS MY_CURRENT_AGE; -- IT ALLOWS US TO FIND OUT THE DIFFERENCE BETWEEN TWO DATES
SELECT ISDATE('2025-08-14') AS ActualDate, ISDATE('ABC') AS NotADate; -- WE USE THIS ONE TO VALIDATE WHETHER A VALUE IS DATE OR NOT

--4] NULL FUNCTIONS
SELECT ShipAddress, ISNULL(ShipAddress, 'N/A') FROM Sales.Orders; --IT REPLACES 'NULL' WITH A SPECIFIED VALUE
SELECT ShipAddress, BillAddress, COALESCE(ShipAddress, BillAddress, 'NOT PROVIDED') FROM Sales.Orders; -- IT RETURNS THE FIRST NON-NULL VALUE, IT IS AS WELL SIMILAR TO ISNULL
SELECT BillAddress, ShipAddress, NULLIF(BillAddress, ShipAddress) FROM Sales.Orders; -- RETURN'S NULL IF TWO VALUES ARE EQUAL AND RETURN'S FIRST VALUE IF THE TWO VALUES ARE NOT EQUAL
SELECT * FROM Sales.Customers WHERE Score IS NULL; -- IS NULL, WILL RETURNS TRUE IF THE VALUE IS NULL AND RETURNS FALSE IF THE VALUE IS FALSE
SELECT * FROM Sales.Customers WHERE Score IS NOT NULL; -- IS NOT NULL, RETURNS TRUE IF THE VALUE IS NOT NULL AND RETURNS FALSE IF THE VALUE IS NULL

--5] CASE STATEMENTS
SELECT OrderID, Sales, (CASE WHEN Sales >= 50 THEN 'HIGH'  WHEN Sales > 30 THEN 'MEDIUM'  ELSE 'LOW' END) SaleCategory FROM Sales.Orders;
SELECT (CASE WHEN Gender = 'M' THEN 'MALE'  ELSE 'FEMALE' END) AS GENDER, COUNT((CASE WHEN Gender = 'M' THEN 'MALE'  ELSE 'FEMALE' END)) AS GENDER_COUNT FROM Sales.Employees GROUP BY GENDER;

