USE SalesDB;

SELECT * FROM Sales.Orders;

-----------------------------------------SYNTAX OF A WINDOW FUNCTION QUERY----------------------------------
-- F(X) OVER(PARTITION CLAUSE ORDER BY CLAUSE FRAME CLAUSE);
-- AVG(Sales) OVER (PARTITION BY Category ORDER BY OrderDate ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING);
-------------------------------------------------------------------------------------------------------------

-- WINDOW FUNCTIONS --> WINDOW FUNCTIONS RETURNS RESULTS FOR EACH ROW
--1] NORMAL AGGERIGATION RESULTS 
SELECT SUM(Sales) AS TotalSales FROM Sales.Orders; -- ONLY 1 RESULT

--2] WINDOW FUNCTION AGGREGATE RESULTS
SELECT ProductID, SUM(Sales) OVER(PARTITION BY ProductID) AS TotalSales FROM Sales.Orders; -- NO OF RESULTS SAME AS NO OF ROWS

--3] FIND THE TOTAL SALES ACROSS ALL ORDERS ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID & ORDERDATE
SELECT OrderID, OrderDate, SUM(Sales) OVER() ParticularSale FROM Sales.Orders;

--4] FIND THE TOTAL SALES FOR EACH PRODUCT, ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID & ORDERDATE
SELECT OrderID, ProductID, OrderDate, SUM(Sales) OVER(PARTITION BY ProductID) ParticularSale FROM Sales.Orders;

--5] FIND THE TOTAL SALES FOR EACH PRODUCT AS WELL AS FIND THE TOTAL SALES FOR EACH ORDER, ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID, PRODUCTID & ORDERDATE
SELECT OrderID, ProductID, OrderDate, SUM(Sales) OVER(PARTITION BY ProductID) Product_ParticularSale, SUM(Sales) OVER(PARTITION BY OrderID) Order_ParticularSale FROM Sales.Orders;

--6] FIND THE TOTAL SALES FOR EACH COMBINATION OF PRODUCT AND ORDER STATUS, ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID, PRODUCTID, ORDERSTATUS & ORDERDATE
SELECT OrderID, ProductID, OrderDate, OrderStatus, SUM(Sales) OVER(PARTITION BY ProductID, OrderStatus) AS SalesByProdIDandStatus FROM Sales.Orders;

--7] RANK EACH ORDER BY SALES FROM THE HIGHEST TO THE LOWEST ALSO PROVIDE ADDITONAL INFO SUCH AS ORDERID, ORDERDATE, SALES
SELECT OrderID, OrderDate, Sales, RANK() OVER(ORDER BY Sales DESC) SaleRank FROM Sales.Orders;

--8] EXAMPLES OF WINDOW FUNCTION QUERIES
SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus) FROM Sales.Orders; -- JUST PARTITION CLAUSE
SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderID DESC) RunningAverage FROM Sales.Orders; -- WITH PARTITION AND ORDER BY CLAUSE
SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderID DESC ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) TWO_YEAR_MOVING_AVERAGE FROM Sales.Orders; -- WITH PARTITION, ORDER BY AND FRAME CLAUSE

SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderID DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) THREE_YEAR_MOVING_AVERAGE FROM Sales.Orders; -- WITH PARTITION, ORDER BY AND FRAME CLAUSE

SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderID DESC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) SOME_AVERAGE FROM Sales.Orders; -- WITH PARTITION, ORDER BY AND FRAME CLAUSE

SELECT OrderID, OrderDate, OrderStatus, Sales, AVG(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderID DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) OrderStatus_Avergae FROM Sales.Orders; -- WITH PARTITION, ORDER BY AND FRAME CLAUSE


--9] AGGREGATE WINDOW FUNCTIONS
SELECT ProductID, Sales, SUM(Sales) OVER() AS TotalSales, SUM(Sales) OVER(PARTITION BY ProductID ORDER BY ProductID DESC)AS TotalSalesByProduct, RANK() OVER(ORDER BY Sales) FROM Sales.Orders;
SELECT Sales, OrderStatus, SUM(Sales) OVER (PARTITION BY OrderStatus) FROM Sales.Orders;
SELECT CustomerID, OrderStatus, COUNT(Sales) OVER (PARTITION BY CustomerID) AS No_of_orders FROM Sales.Orders; -- IDENTIFYING DUPLICATE ROWS USING WINDOW FUNCTIONS 
SELECT Sales, OrderStatus, AVG(Sales) OVER (PARTITION BY OrderStatus) FROM Sales.Orders;
SELECT ProductID, OrderID, OrderStatus, Sales, MAX(Sales) OVER(PARTITION BY OrderStatus) AS OVERALL_MAX_SALES FROM Sales.Orders;
SELECT ProductID, OrderID, OrderStatus, Sales, MIN(Sales) OVER(PARTITION BY OrderStatus) AS OVERALL_MIN_SALES FROM Sales.Orders;

-- 10] WINDOW RANK FUNCTIONS
SELECT OrderID, ProductID, Sales, ROW_NUMBER() OVER(ORDER BY Sales DESC) TOP_SALES_BY_RANK FROM Sales.Orders; -- SAME VALUES WILL BE STILL BE RANKED WITH UNIQUE RANKS
SELECT OrderID, ProductID, Sales, RANK() OVER(ORDER BY Sales DESC) TOP_SALES_BY_RANK FROM Sales.Orders; -- SAME VALUES WILL BE RANKED WITH COMMON RANK AMD ALSO IT WILL LEAVE GAPS IN RANK
SELECT OrderID, ProductID, Sales, DENSE_RANK() OVER(ORDER BY Sales DESC) TOP_SALES_BY_RANK FROM Sales.Orders; -- SAME VALUES WILL BE RANKED WITH COMMON RANK BUT IT WILL NOT LEAVE ANY GAPS IN RANK
SELECT OrderID, ProductID, Sales, NTILE(2) OVER(ORDER BY Sales DESC) FROM Sales.Orders; -- DIVIDES THE DATA INTO MULTIPLE BUCKETS OF GIVEN SIZE, USEFUL FOR DATA SEGMENTATION. IT ALSO PLAYS A VERY IMPORT ROLE WHEN WE HAVE TO EXPORT DATA FROM ONE DATABASE TO ANOTHER DATABASE AND TO DO THAT WE SPLIT THE TABLE INTO MULTIPLE MINI SEGMENTS USING THE NTILE FUNCTION AND THEN EXPORT IT AND THEN AT THE RECIVEING END USE THE UNION FUNCTION AGAIN TO MERGE ALL THE MINI SEGMENTS INTO ORIGINAL DATA TABLE
SELECT OrderID, ProductID, Sales, CUME_DIST() OVER(ORDER BY Sales DESC) FROM Sales.Orders;  -- RANKS THE ROWS WITH THE PERCENTAGES BETWEEN 0 TO 1, INSTEAD OF GIVING INTEGER RANKS AS PREVIOUS RANK FUNCTIONS DID
SELECT OrderID, ProductID, Sales, ROUND(PERCENT_RANK() OVER(ORDER BY Sales DESC), 2) FROM Sales.Orders;  -- RANKS THE ROWS WITH THE PERCENTAGES BETWEEN 0 TO 1, INSTEAD OF GIVING INTEGER RANKS AS PREVIOUS RANK FUNCTIONS DID. [SAME AS CUME_RANK()]

--11] WINDOW VALUE FUNCTIONS
SELECT OrderID, ProductID, Sales, LAG(Sales,1) OVER(ORDER BY Sales DESC) Previous_row_values FROM Sales.Orders; -- ACCESS A VALUE FROM THE PREVIOUS ROW WITHIN A WINDOW
SELECT OrderID, ProductID, Sales, LEAD(Sales,1) OVER(ORDER BY Sales DESC) Next_row_values FROM Sales.Orders; -- ACCESS A VALUE FROM THE NEXT ROW WITHIN A WINDOW
SELECT OrderID, ProductID, Sales, LAST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales DESC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) Comparision_with_LastRowValue FROM Sales.Orders; -- ACCESS A VALUE FROM THE LAST ROW WITHIN A WINDOW
SELECT OrderID, ProductID, Sales, FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales DESC) Comparision_with_FirstRowValue FROM Sales.Orders; -- ACCESS A VALUE FROM THE FIRST ROW WITHIN A WINDOW

-- 12] MISCELLANEOUS BUSINESS PROBLEMS PRACTICE QUERIES USING WINDOW FUNCTIONS TO ACHEIVE BUSINESS CENTRIC SOLUTIONS. 
SELECT * FROM(
SELECT OrderID, ProductID, Sales, AVG(Sales) OVER() AVG_SALE FROM Sales.Orders
)t WHERE Sales > AVG_SALE;

SELECT FirstName, LastName, Salary FROM(
SELECT FirstName, ISNULL(LastName, 'Not_Known') LastName, Salary, MAX(Salary) OVER() AS MaxSalary FROM Sales.Employees
)t WHERE Salary = MaxSalary;

SELECT *, (CASE WHEN Buckets = 1 THEN 'HIGH' WHEN Buckets = 2 THEN 'MEDIUM' WHEN Buckets = 3 THEN 'LOW' END) SEGMENTATION FROM(
SELECT OrderID, ProductID, Sales, NTILE(3) OVER(ORDER BY Sales DESC) Buckets FROM Sales.Orders
)t;

