-- CREATE TABLE AS SELECT (CTAS) --
USE SalesDB;

-------------------------------- CTAS SYNTAX --------------------------------
SELECT EmployeeID, FirstName 
INTO Sales.CTAS_Emp_table -- CREATING CTAS TABLE
FROM Sales.Employees;

SELECT * FROM Sales.CTAS_Emp_table; -- DISPLAYING CTAS TABLE

DROP TABLE Sales.CTAS_Emp_table; -- DROP CTAS TABLE

--1] CTAS IS COMPARITIVELY FASTER THAN VIEWS FOR THE END USERS TO ACCESS THE DATA QUICKLY 
--2] CTAS TABLE ONCE CREATED WILL REMAIN STATIC AND ANY CHANGES IN THE ORIGINAL TABLE WILL NOT BE REFLECTED IN THE CTAS TABLE, WHICH IS NOT THE CASE WITH VIEWS. 
--3] TO UPDATE CTAS TABLE WITH FRESH DATA EVERYTIME WE WOULD NEED TO DROP THE TABLE AND CREATE IT AGAIN. 

-------------------------------- CTAS SYNTAX ------------------------------------

-------------------------------- TEMPROARY TABLE --------------------------------
SELECT * 
INTO #Temp_Orders -- CREATING A TEMPROARY TABLE WITH USING '#' BEFORE TABLE NAME
FROM Sales.Orders;

SELECT * FROM #Temp_Orders; -- DISPLAYING TEMP TABLE CONTENTS 


--1] ALL THE TEMPROARY TABLES WILL BE STORED IN A SPECIAL DATABASE IN SQLSERVER KNOWN AS 'tempdb'
--2] AFTER THE SESSION IS OVER, ALL THE TEMPROARY TABLES WILL BE DESTROYED
--3] TEMPROARY TABLES ARE BEST USED FOR CREATING REPLICA'S OR COPY'S OF ORIGINAL DATA AND STORING IT SOMEWHERE ELSE AND PERFORMING ALL OPERATIONS ON THAT COPY BEFORE WORKING ON ORIGINAL DATA
--4] TEMPROARY TABLES PLAY IMPORTANT PART IN THE EXTRACT TRANSFORM LOAD(ETL) PROCESS. 
-------------------------------- TEMPROARY TABLE --------------------------------
